# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
system-ghc: false

extra-include-dirs:
  - /usr/local/opt/openssl/include

extra-lib-dirs:
  - /usr/local/opt/openssl/lib

# jobs: 4
